spring:
  application:
    name: weather-gateway
server:
  port: 80
zuul:
  routes:
    report:
      path: /report/**
      serviceID: weather-report-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}