spring:
  application:
    name: weather-report-service
server:
  port: 9300
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/