spring:
  application:
    name: weather-data-service-collection
server:
  port: 9100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
feign:
  client:
    config:
      feignName:
        connectionTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
